### PR TITLE
Tests for gog price comparison

### PR DESCRIPTION
**Pull request by AHuang170**

### CODE REVIEW

**Comment by EXcurrybat** [comment]
[Create unit tests for gameloop function](https://trello.com/c/KqXYwgoF/48-create-unit-tests-for-gameloop-function)

**Comment by EXcurrybat** [comment]
[Write function to extract game object from an array based on game name](https://trello.com/c/boW2GeFF/72-write-function-to-extract-game-object-from-an-array-based-on-game-name)

**Comment by EXcurrybat** [comment]
[Create function to pull GOG data](https://trello.com/c/I0ApInl3/38-create-function-to-pull-gog-data)

**Comment by EXcurrybat** [comment]
[Change steam and gameloop functions to also include pulling from GOG](https://trello.com/c/LU8PlcHH/39-change-steam-and-gameloop-functions-to-also-include-pulling-from-gog)

**Comment by EXcurrybat** [comment]
[Function to compare prices](https://trello.com/c/XLG7jz1B/42-function-to-compare-prices)

**Comment by EXcurrybat** [comment]
[Create function to parse GOG object](https://trello.com/c/V7YTcq0T/41-create-function-to-parse-gog-object)

**Comment by AHuang170** [comment]
[Create unit tests for GOG/Steam price comparison](https://trello.com/c/Fc694ucR/44-create-unit-tests-for-gog-steam-price-comparison)

**Comment by AHuang170** [comment]
[Create unit tests for game objection extraction based on name](https://trello.com/c/gdm8cITz/71-create-unit-tests-for-game-objection-extraction-based-on-name)

**Comment by AHuang170** [comment]
[Create unit tests for GOG object parsing](https://trello.com/c/XsXcl263/45-create-unit-tests-for-gog-object-parsing)

**Pull request merged**
